name: Update Docker Hub Description

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-hub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update service description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: digiwells/osdcdrillingearthverticaldatumservice
          readme-filepath: ./Service/README.md
      - name: Update WebApp description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: digiwells/osdcdrillingearthverticaldatumwebappclient
          readme-filepath: ./WebApp/README.md
